version: '3'
services:

  mongo:
    image: mongo:3.6
    volumes:
      - mongo-storage:/data/db # Nous pouvons ajouter un volume à ce container afin de stocker les données de la base
    expose:
      - 27017
    ports:
      - 27018:27017

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    devices: #map Serial port for arduino connection
      - "/dev/ttyACM0:/dev/ttyACM0"
      # "/COM4:/COM4"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment: 
      - MONGO_URL=mongodb://mongo/arduino
      - PORT=5000

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - "server:se"

# Définition des volumes:
volumes:
  mongo-storage:
    driver: local